- menu_name: "Social Media"

# - name: "Contact"
#   url: "/contact/"
#   title: "Contact"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

- name: "Twitter"
  url: "https://twitter.com/wenjunchen_alex"
